---
version: '2'
services:
  presto:
    image: prestodb/presto:latest
    container_name: presto
    volumes:
      - ./coordinator/config.properties:/opt/presto-server/etc/config.properties
      - ./coordinator/jvm.config:/opt/presto-server/etc/jvm.config
      - ./config/catalog/mongodb.properties:/opt/presto-server/etc/catalog/mongodb.properties
      - ./config/catalog/mysql.properties:/opt/presto-server/etc/catalog/mysql.properties
      - ./config/catalog/postgresql.properties:/opt/presto-server/etc/catalog/postgresql.properties
      - ./config/catalog/cassandra.properties:/opt/presto-server/etc/catalog/cassandra.properties
      - ./config/catalog/tpcds.properties:/opt/presto-server/etc/catalog/tpcds.properties
    ports:
      - "8080:8080"
    networks:
      - presto-nw

  mongodb:
    image: mongo:6.0.4
    container_name: presto-mongo
    volumes:
      - mongoData:/data/db
    ports:
      - "27017:27017"
    networks:
      - presto-nw
  
  postgresql:
    image: postgres
    container_name: presto-postgresql
    environment:  
      POSTGRES_USER: root
      POSTGRES_PASSWORD: presto
      POSTGRES_DB: presto
    ports:
      - "5432:5432"
    networks:
      - presto-nw 

  cassandra:
    image: cassandra:latest
    container_name: presto-cassandra
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - presto-nw

networks:
  presto-nw:
    driver: bridge

volumes:
  mongoData:
  cassandra-data:
  