version: '3.9'

services:
  coordinator:
    image: prestodb/presto:latest
    volumes:
      - ./coordinator/config.properties:/opt/presto-server/etc/config.properties
      - ./coordinator/node.properties:/opt/presto-server/etc/node.properties
      - ./config/catalog/mongodb.properties:/opt/presto-server/etc/catalog/mongodb.properties
      - ./config/catalog/postgresql.properties:/opt/presto-server/etc/catalog/postgresql.properties
      - ./config/catalog/cassandra.properties:/opt/presto-server/etc/catalog/cassandra.properties
      - ./config/catalog/tpcds.properties:/opt/presto-server/etc/catalog/tpcds.properties
    ports:
      - "8080:8080"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77184

  worker_1:
    image: prestodb/presto:latest
    volumes:
      - ./workers/config.properties:/opt/presto-server/etc/config.properties
      - ./workers/1/node.properties:/opt/presto-server/etc/node.properties
      - ./config/catalog/mongodb.properties:/opt/presto-server/etc/catalog/mongodb.properties
      - ./config/catalog/postgresql.properties:/opt/presto-server/etc/catalog/postgresql.properties
      - ./config/catalog/cassandra.properties:/opt/presto-server/etc/catalog/cassandra.properties
      - ./config/catalog/tpcds.properties:/opt/presto-server/etc/catalog/tpcds.properties
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77183

  mongodb:
    image: mongo:6.0.4
    volumes:
      - mongoData:/data/db
    ports:
      - "27017:27017"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77184

  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: presto
      POSTGRES_DB: presto
    ports:
      - "5432:5432"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77184

  cassandra:
    image: cassandra:latest
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77183

networks:
  overnet:
    external: true

volumes:
  mongoData:
  cassandra-data:
