version: '3.9'

services:
  presto:
    image: prestodb/presto:latest
    container_name: presto
    volumes:
        - ./config/catalog:/opt/presto-server/etc/catalog
        - ./coordinator/jvm.config:/opt/presto-server/etc/jvm.config
        - ./coordinator/presto-benchmark-driver:/opt/benchmark-driver/presto-benchmark-driver
        - ./Queries:/opt/benchmark-driver/sql
        - ./coordinator/suite.json:/opt/benchmark-driver/suite.json
        - ./coordinator/config.properties:/opt/presto-server/etc/config.properties
    ports:
        - target: 8080
          published: 8080
          protocol: tcp
          mode: host
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77266
  mongodb:
    image: mongo
    container_name: presto-mongo
    volumes:
      - mongoData:/data/db
    ports:
      - "27017:27017"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77266
  postgresql:
    image: postgres
    container_name: presto-postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: presto
      POSTGRES_DB: presto
    ports:
      - "5432:5432"
    networks:
      - overnet
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77284

  cassandra:
    image: cassandra:latest
    container_name: presto-cassandra
    environment:
      CASSANDRA_USER: admin
      CASSANDRA_PASSWORD: admin
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77267

networks:
  overnet:
    external: true

volumes:
  mongoData:
  cassandra-data:
  postgresql-data:
