version: '3.9'

services:
  presto:
    image: prestodb/presto:latest
    container_name: presto-coordinator
    volumes:
      - ./config/catalog:/opt/presto-server/etc/catalog
      - ./coordinator/jvm.config:/opt/presto-server/etc/jvm.config
      - ./coordinator/presto-benchmark-driver:/opt/benchmark-driver/presto-benchmark-driver
      - ./Queries:/opt/benchmark-driver/sql
      - ./coordinator/suite.json:/opt/benchmark-driver/suite.json
      - ./coordinator/config.properties:/opt/presto-server/etc/config.properties
    ports:
      - "8080:8080"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77266
  # Presto Worker 1
  presto-worker-1:
    image: prestodb/presto:latest
    container_name: presto-worker-1
    volumes:   
      - ./config/catalog:/opt/presto-server/etc/catalog
      - ./workers/jvm.config:/opt/presto-server/etc/jvm.config
      - ./workers/config.properties:/opt/presto-server/etc/config.properties
      - ./workers/1/node.properties:/opt/presto-server/etc/node.properties
    environment:
      PRESTO_COORDINATOR_HOST: presto-coordinator
    ports:
      - "8081:8081"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77267

  # Presto Worker 2
  presto-worker-2:
    image: prestodb/presto:latest
    container_name: presto-worker-2
    volumes:
      - ./config/catalog:/opt/presto-server/etc/catalog
      - ./workers/jvm.config:/opt/presto-server/etc/jvm.config
      - ./workers/config.properties:/opt/presto-server/etc/config.properties
      - ./workers/2/node.properties:/opt/presto-server/etc/node.properties
    environment:
      PRESTO_COORDINATOR_HOST: presto-coordinator
    ports:
      - "8082:8082"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77284


  mongodb:
    image: mongo
    container_name: presto-mongo
    volumes:
      - mongoData:/data/db
    ports:
      - "27017:27017"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77266
  postgresql:
    image: postgres
    container_name: presto-postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: presto
      POSTGRES_DB: presto
    ports:
      - "5432:5432"
    networks:
      - overnet
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77284

  cassandra:
    image: cassandra:latest
    container_name: presto-cassandra
    environment:
      CASSANDRA_USER: admin
      CASSANDRA_PASSWORD: admin
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - overnet
    deploy:
      placement:
        constraints:
          - node.hostname == snf-77267

networks:
  overnet:
    external: true

volumes:
  mongoData:
  cassandra-data:
  postgresql-data:
